Events
John-Arboleda/math_magicians pull request #4
Opened 2022-01-08 21:17 UTC by John-Arboleda

# Events

"Math magicians" is a website for all fans of mathematics. It is a Single Page App (SPA) that allows users to:
- Make simple calculations.
- Read a random math-related quote.

### Learning Objectives
- [x] Handle events in a React app.
- [x] Use React life cycle methods.
- [x] Understand the mechanism of lifting state up.

2022-01-08 22:41 UTC, enaburekhan requested changes
Hi John-Arboleda, 

Good job so far!

- [ ] Major highlights

- The PR summary and commit messages are very descriptive.
- The codebase is clean, easy to read and understand.
- Passed all linters checks

However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ] I will suggest you include how to run the application locally in your readme. You can achieve this in your getting started section.

I had to add this comment here because the readme was not part of the below review

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Code review by **Eric Enaburekhan**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-01-08 22:41 UTC, enaburekhan commented on src/components/calculator.js
> +        <button className="buttonAc symbols" type="button" onClick={() => { this.handleStateChange(calculate(this.state, 'AC')); }}>AC</button>
- [ ] Nice job here. I would like to point out here that the highlighted `AC` button is currently not working. I would suggest you recheck the code implementation in the `calculate.js`. I'm sure its function is to clear the screen.

2022-01-08 22:41 UTC, enaburekhan commented on src/components/calculator.js
> +            { next }
- [ ] The total value displayed on the screen, should not include the `operation` symbol. I will suggest you remove it.

![image](https://user-images.githubusercontent.com/51296741/148662058-1fa8b708-e97b-4637-a1d4-00454532f81e.png)

2022-01-09 02:59 UTC, oloomoses approved these changes
Hi @John-Arboleda, 

Well done on making the suggested changes.
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

_Slack: Oloo Moses_
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-09 03:01 UTC, merged

2022-01-09 03:05 UTC, oloomoses commented
Kindly reach dm on slack